#include <linux/sockios.h>
#include "ioc.h"

static struct ioc_map macro_maps[] = {
    { "SIOCADDRT",              SIOCADDRT              },
    { "SIOCDELRT",              SIOCDELRT              },
    { "SIOCRTMSG",              SIOCRTMSG              },
    { "SIOCGIFNAME",            SIOCGIFNAME            },
    { "SIOCSIFLINK",            SIOCSIFLINK            },
    { "SIOCGIFCONF",            SIOCGIFCONF            },
    { "SIOCGIFFLAGS",           SIOCGIFFLAGS           },
    { "SIOCSIFFLAGS",           SIOCSIFFLAGS           },
    { "SIOCGIFADDR",            SIOCGIFADDR            },
    { "SIOCSIFADDR",            SIOCSIFADDR            },
    { "SIOCGIFDSTADDR",         SIOCGIFDSTADDR         },
    { "SIOCSIFDSTADDR",         SIOCSIFDSTADDR         },
    { "SIOCGIFBRDADDR",         SIOCGIFBRDADDR         },
    { "SIOCSIFBRDADDR",         SIOCSIFBRDADDR         },
    { "SIOCGIFNETMASK",         SIOCGIFNETMASK         },
    { "SIOCSIFNETMASK",         SIOCSIFNETMASK         },
    { "SIOCGIFMETRIC",          SIOCGIFMETRIC          },
    { "SIOCSIFMETRIC",          SIOCSIFMETRIC          },
    { "SIOCGIFMEM",             SIOCGIFMEM             },
    { "SIOCSIFMEM",             SIOCSIFMEM             },
    { "SIOCGIFMTU",             SIOCGIFMTU             },
    { "SIOCSIFMTU",             SIOCSIFMTU             },
    { "SIOCSIFNAME",            SIOCSIFNAME            },
    { "SIOCSIFHWADDR",          SIOCSIFHWADDR          },
    { "SIOCGIFENCAP",           SIOCGIFENCAP           },
    { "SIOCSIFENCAP",           SIOCSIFENCAP           },
    { "SIOCGIFHWADDR",          SIOCGIFHWADDR          },
    { "SIOCGIFSLAVE",           SIOCGIFSLAVE           },
    { "SIOCSIFSLAVE",           SIOCSIFSLAVE           },
    { "SIOCADDMULTI",           SIOCADDMULTI           },
    { "SIOCDELMULTI",           SIOCDELMULTI           },
    { "SIOCGIFINDEX",           SIOCGIFINDEX           },
    { "SIOGIFINDEX",            SIOGIFINDEX            },
    { "SIOCSIFPFLAGS",          SIOCSIFPFLAGS          },
    { "SIOCGIFPFLAGS",          SIOCGIFPFLAGS          },
    { "SIOCDIFADDR",            SIOCDIFADDR            },
    { "SIOCSIFHWBROADCAST",     SIOCSIFHWBROADCAST     },
    { "SIOCGIFCOUNT",           SIOCGIFCOUNT           },
    { "SIOCGIFBR",              SIOCGIFBR              },
    { "SIOCSIFBR",              SIOCSIFBR              },
    { "SIOCGIFTXQLEN",          SIOCGIFTXQLEN          },
    { "SIOCSIFTXQLEN",          SIOCSIFTXQLEN          },
    { "SIOCETHTOOL",            SIOCETHTOOL            },
    { "SIOCGMIIPHY",            SIOCGMIIPHY            },
    { "SIOCGMIIREG",            SIOCGMIIREG            },
    { "SIOCSMIIREG",            SIOCSMIIREG            },
    { "SIOCWANDEV",             SIOCWANDEV             },
    { "SIOCOUTQNSD",            SIOCOUTQNSD            },
    { "SIOCGSKNS",              SIOCGSKNS              },
    { "SIOCDARP",               SIOCDARP               },
    { "SIOCGARP",               SIOCGARP               },
    { "SIOCSARP",               SIOCSARP               },
    { "SIOCDRARP",              SIOCDRARP              },
    { "SIOCGRARP",              SIOCGRARP              },
    { "SIOCSRARP",              SIOCSRARP              },
    { "SIOCGIFMAP",             SIOCGIFMAP             },
    { "SIOCSIFMAP",             SIOCSIFMAP             },
    { "SIOCADDDLCI",            SIOCADDDLCI            },
    { "SIOCDELDLCI",            SIOCDELDLCI            },
    { "SIOCGIFVLAN",            SIOCGIFVLAN            },
    { "SIOCSIFVLAN",            SIOCSIFVLAN            },
    { "SIOCBONDENSLAVE",        SIOCBONDENSLAVE        },
    { "SIOCBONDRELEASE",        SIOCBONDRELEASE        },
    { "SIOCBONDSETHWADDR",      SIOCBONDSETHWADDR      },
    { "SIOCBONDSLAVEINFOQUERY", SIOCBONDSLAVEINFOQUERY },
    { "SIOCBONDINFOQUERY",      SIOCBONDINFOQUERY      },
    { "SIOCBONDCHANGEACTIVE",   SIOCBONDCHANGEACTIVE   },
    { "SIOCBRADDBR",            SIOCBRADDBR            },
    { "SIOCBRDELBR",            SIOCBRDELBR            },
    { "SIOCBRADDIF",            SIOCBRADDIF            },
    { "SIOCBRDELIF",            SIOCBRDELIF            },
    { "SIOCSHWTSTAMP",          SIOCSHWTSTAMP          },
    { "SIOCGHWTSTAMP",          SIOCGHWTSTAMP          },
    { "SIOCDEVPRIVATE",         SIOCDEVPRIVATE         },
    { "SIOCPROTOPRIVATE",       SIOCPROTOPRIVATE       },
    { NULL,                     0                      }
};


int
ioc_macro_value_sockios (char *macro_name)
{
    return query_map(macro_maps, macro_name);
}
